# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- master

steps:
- task: StartSandbox@0
  name: 'Torque'
  inputs:
    torqueEndpoint: 'Torque-Dmytro'
    timeout: '20'
    space: 'Sample'
    blueprint: '[Sample]Bitnami Nginx Helm Chart'
    sandbox: 'aece'
    inputs: 'replicaCount=1'
- task: EndSandbox@0
  inputs:
    torqueEndpoint: 'Torque-Dmytro'
    space: 'Sample'
    sandboxId: '$(Torque.Sandbox_Id)'
